### ISSUE TITLE
Trinkets Curios Theme Compatibility [COULD FIX TRINKETS API ISSUE]

### ISSUE THREAD

**Issue by ConqAra** [RubixDev/Inventorio#129]
This might actually be the way to have people see the inventorio inventory with trinkets by adding support for this mod! With the way it works, I think this might work if implementations and support were worked on right?! [I've also posted this issue with the mod dev
](https://github.com/jptrzy/trinkets-curios-theme-mod/issues/3)

![image](https://user-images.githubusercontent.com/76233356/178090053-8fde37ef-3a30-4315-a16e-ff713f7242ba.png)

**Comment by Lizard-Of-Oz** [comment]
As much as I'd like to bring compatibility with popular mods like Trinkets, I don't have time to do so.

My hopes is that once I set up a donation page (should be coming in a week or two), people might consider supporting my financially, so that I could rework the entire mod to make it better and more compatible with other mods.

I have many plans how to take Inventorio forward, but let's see if they are destined to be.

**Comment by Delfite** [comment]
@Lizard-Of-Oz Well if you're not going to permanently fix this issue for now, can you at least add a button to swap between the normal inventory and Inventorio's? Last time I tried removing an inventory-related mod that interfered with Trinkets my world became permanently unrecoverable.

**Comment by Lizard-Of-Oz** [comment]
Such a button already exists on the top-right corner of the player inventory ui. Welp, it seems like in your case there's also something else precisely in that place.

**Comment by RubixDev** [comment]
Closing in favor of #318
