### ISSUE TITLE
Not compatible with "You're in grave danger" mod.

### ISSUE THREAD

**Issue by RaulWIlliamC** [RubixDev/Inventorio#310]
Doesn't work with you're in grave danger mod. When you die, the items in the belt slot disappears upon recovering your gravestone.

**Comment by JustCallMeAz** [comment]
In my experience, it cause the game to crash.
From what I understand, when "You're in grave danger" try to 'getInventory', due to inventorio way to upgrade the inventory, it simply can't get it and throw a fatal error.

Here is a short crash log : 
[crash log : inventorio youre in grave danger.txt](https://github.com/RubixDev/Inventorio/files/14736309/crash.inventorio.youre.in.grave.danger.txt)

**Comment by JustCallMeAz** [comment]
But, what I do not understand is that the mod [You're in grave danger](https://modrinth.com/mod/yigd) clearly say : 

> The mod aims to be compatible with most, if not all inventory mods. Currently You're in Grave Danger provides compat for: inventorio [all versions], trinkets [all versions], curios [1.16], travelers backpack [1.16, 1.17]

**Comment by RubixDev** [comment]
while I don't quite understand why that exact crash happened, this has been fixed on their end https://github.com/B1n-ry/Youre-in-grave-danger/issues/157
