### ISSUE TITLE
Incompatible with Tweakermore

### ISSUE THREAD

**Issue by aMazeInRunar** [RubixDev/Inventorio#328]
Fabric 1.20.1 
Inventorio v1.10.1
Tweakermore v3.17.0
Should I open an issue on Tweakermore's page too?

[crash-2024-03-29_15.44.58-client.txt](https://github.com/RubixDev/Inventorio/files/14805349/crash-2024-03-29_15.44.58-client.txt)

**Comment by RubixDev** [comment]
yikes, that's unfortunate. For context, both Inventorio and Tweakermore use (and bundle) [conditional-mixin](https://github.com/Fallen-Breath/conditional-mixin), however Inventorio requires v0.6.0 which [introduced (Neo)Forge support](https://github.com/Fallen-Breath/conditional-mixin/pull/5) while Tweakermore is still using v0.5.1. The Fabric loader sees both versions and chooses the newer one, which had breaking API changes. Although conditional-mixin tried to keep the old API compatible with the update, so that's actually an issue I will report over there. So the proper fix for this is either Tweakermore updating to conditional-mixin v0.6.0 or fixing conditional-mixin's backwards compatibility. Preferably both.

**Comment by RubixDev** [comment]
Oh wait, Fallen-Breath already fixed this in conditional-mixin yesterday. I'll quickly publish a hotfix with the new version.
